name = "gfelmer"
location = "westus2"
ippublica = "ippublicacmp"
network = "gfelmernetwork"
subnet = "gfelmersubnet"
container = "containerRegistrygfelmer"
aks = "aksgfelmer"
kubernets_version = "1.19.6"
